services:
    dhiarlink_db_mysql:
        user: '0'
        environment:
            MYSQL_DATABASE: dhiarlink_test

    dhiarlink_db_postgres:
        user: '0'
        environment:
            POSTGRES_DB: dhiarlink_test

    dhiarlink_db_maria:
        user: '0'
        environment:
            MYSQL_DATABASE: dhiarlink_test
